In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

/home/student/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [2]:
data = pd.read_csv("/home/student/Downloads/play_tennis.csv")
data

day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   day       14 non-null     object
 1   outlook   14 non-null     object
 2   temp      14 non-null     object
 3   humidity  14 non-null     object
 4   wind      14 non-null     object
 5   play      14 non-null     object
dtypes: object(6)
memory usage: 800.0+ bytes


In [4]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
py = 9/14
pn = 5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715


# Starting training phase

In [6]:
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook          
Overcast   0    4
Rain       2    3
Sunny      3    2

In [7]:
pon = 0
prn = 2/5
psn = 3/5
poy = 4/9
pry = 3/9
psy = 2/9

In [8]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp         
Cool   1    3
Hot    2    2
Mild   2    4

In [9]:
pcoolno = 1/5
photno = 2/5
pmildno = 2/5
pcoolyes = 3/9
photyes = 2/9
pmildyes = 4/9

In [10]:
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity         
High       4    3
Normal     1    6

In [11]:
phighno = 4/5
pnormalno = 1/5
phighyes = 3/9
pnormalyes = 6/9

In [12]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind           
Strong   3    3
Weak     2    6

In [13]:
pstrongno = 3/5
pweakno = 2/5
pstrongyes = 3/5
pweakyes = 6/9

In [14]:
pyes = py * psy * photyes * phighyes * pweakyes
print(pyes)

0.007054673721340388


In [15]:
pno = pn * psn * photno * phighno * pweakno
print(pno)

0.02742857142857143


In [16]:
data['outlook'].value_counts()

outlook
Sunny       5
Rain        5
Overcast    4
Name: count, dtype: int64

In [17]:
osunny = 5/14
orain = 5/14
oovercast = 4/14

In [18]:
pd.crosstab(data['play'], data['outlook'])

outlook  Overcast  Rain  Sunny
play                          
No              0     2      3
Yes             4     3      2

In [19]:
ooverno = 0
ooveryes = 4/4
orainno = 2/5
orainyes = 3/5
osunnyno = 3/5
osunnyyes = 2/5

In [20]:
pd.crosstab(data['temp'], data['outlook'])

outlook  Overcast  Rain  Sunny
temp                          
Cool            1     2      1
Hot             2     0      2
Mild            1     3      2

In [21]:
pd.crosstab(data['humidity'], data['outlook'])

outlook   Overcast  Rain  Sunny
humidity                       
High             2     2      3
Normal           2     3      2

In [22]:
pd.crosstab(data['wind'], data['outlook'])

outlook  Overcast  Rain  Sunny
wind                          
Strong          2     2      2
Weak            2     3      3

In [23]:
oovercool = 1/4
oovernormal = 2/4
ooverweak = 2/4

In [24]:
outyes = oovercast * ooveryes * oovercool * oovernormal * ooverweak

In [25]:
outyes

0.017857142857142856

In [26]:
outno = oovercast * ooverno * oovercool * oovernormal * ooverweak

In [27]:
outno

0.0

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
label_encoder = LabelEncoder()

In [38]:
data['day'] = label_encoder.fit_transform(data['day'])

In [39]:
data['day']

0      0
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9      1
10     2
11     3
12     4
13     5
Name: day, dtype: int64

In [40]:
X = np.array(data[['day']])

In [41]:
X

array([[ 0],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5]])

In [42]:
Y = label_encoder.fit_transform(data['play'])

In [43]:
Y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [44]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 10)

In [45]:
X_train.shape

(10, 1)

In [46]:
log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)

LogisticRegression()

In [47]:
Y_pred = log_reg.predict(X_test)

In [48]:
confusion_matrix(Y_test, Y_pred)

array([[0, 1],
       [0, 3]])

In [49]:
accuracy = accuracy_score(Y_test, Y_pred)
print('Accuracy is ', accuracy)

Accuracy is  0.75


In [50]:
precision = precision_score(Y_test, Y_pred)
print('Precision is', precision)

Precision is 0.75


In [51]:
recall = recall_score(Y_test, Y_pred)
print('Recall is', recall)

Recall is 1.0
